// Generated by https://quicktype.io

export interface IVoter {
  id: number;
  pollingStation: string;
  voterID: string;
  age: string;
  dateOfBirth: string;
  sex: string;
  regDate: string;
  fullname: string;
  picture: string;
  fathersName: string;
  mothersName: string;
  residentialAddress: string;
  createdUser: string;
}
