// Generated by https://quicktype.io

export interface IPassport {
  id: number;
  passportNo: string;
  firstName: string;
  lastName: string;
  middleName: string;
  nationality: string;
  dateOfBirth: string;
  gender: string;
  placeOfBirth: string;
  placeOfIssue: string;
  issueDate: string;
  expiryDate: string;
  picture: string;
  signature: string;
  createdUser: string;
}
